const TX={
"title": "Чайна зала",
"tagline": "Підбери кожному гостю його чай",
"btn_continue": "Продовжити гру",
"btn_new": "Нова гра",
"btn_dex": "Довідник чаїв",
"btn_how": "Як грати",
"best_line": "Найкращий рахунок: {n}",
"btn_menu": "Меню",
"aria_home": "Вийти в меню. Гру збережено",
"lvl_normal": "Рівень {level}, до нового чаю {p}/{per}",
"prog_normal": "У меню {m} з {total}",
"lvl_endless": "Безкінечний режим",
"prog_endless": "Усі чаї у меню, гостей: {n}",
"aria_lives": "Життя: {n} з {max}",
"aria_patience": "Терпіння: {n} з {max}",
"aria_hidden": "Прихований пункт",
"aria_tried": "уже пробували",
"aria_search": "Пошук",
"tray_title": "Твоє меню",
"toggle_easy": "Підказки на картках",
"filter_all": "Усі",
"search_name": "Пошук за назвою",
"search_deep": "Пошук за назвою, смаком, регіоном",
"empty": "Нічого не знайдено. Зміни фільтр.",
"msg_start": "Торкнись картки чаю, щоб побачити деталі й подати його гостю.",
"msg_wrong": "«{tea}» не підійшов.",
"msg_mismatch": "Не збігається: {list}.",
"msg_revealed": "Гість уточнив: {trait}.",
"msg_win": "«{tea}» — саме те! +{pts}",
"msg_perfect": "Із першої спроби.",
"msg_life": "Життя повернулось: +♥.",
"msg_lose": "Терпіння скінчилось, гість пішов. Йому підійшов би «{tea}».",
"stamp_win": "Смачно!",
"stamp_lose": "Пішов",
"btn_next": "Наступний гість",
"btn_summary": "Підсумок",
"need_label": "Гість хоче",
"btn_serve": "Подати гостю",
"btn_tried": "Цей чай уже пробували",
"btn_close": "Закрити",
"btn_ok": "Зрозуміло",
"btn_to_guests": "До гостей",
"label_novice": "Для новачків",
"prop_time": "Час доби",
"prop_vessel": "Посуд",
"prop_weight": "Вага",
"prop_temp": "Температура",
"prop_infusions": "Проливи",
"prop_pour": "Злив",
"about_h": "Про чай",
"unlock_new_title": "Меню поповнилось",
"unlock_new_body": "У меню з’явився новий чай. Знайди його серед карток.",
"unlock_last_title": "Усі чаї відкрито",
"unlock_last_body": "Останній чай додано до меню. Тепер гра безкінечна, доки не скінчаться життя.",
"dex_title": "Довідник чаїв",
"btn_back": "Назад",
"over_title": "Чайна зала зачиняється",
"over_record": "Новий рекорд",
"stat_score": "Рахунок",
"stat_served": "Обслужено гостей",
"stat_menu": "Чаїв у меню",
"stat_menu_value": "{m} з {total}",
"stat_perfect": "З першої спроби",
"stat_best": "Найкращий рахунок",
"btn_again": "Нова гра",
"btn_home": "Головне меню",
"howto_title": "Як грати",
"howto_1": "Гість приходить із побажаннями: смак, регіон, а також температура води 🌡 і кількість проливів 🔁. Пункт «???» прихований, гість розкриє його, коли ти помилишся.",
"howto_2": "Обери категорію чаю. З’являться маленькі картки: «Інфо» показує деталі, «Подати» дає чай гостю, ✕ закриває список.",
"howto_3": "Кожна помилка забирає терпіння ☕ і розкриває один прихований пункт. Коли терпіння скінчилось, гість іде, і ти втрачаєш ♥.",
"howto_4": "Кожні {per} обслужених гостей у меню з’являється новий чай. Коли відкриті всі, починається безкінечний режим.",
"howto_5": "Кожні {perfects} гостей, обслужених із першої спроби, повертають одне життя.",
"howto_6": "Після правильного чаю можна заварити його: обрати температуру води й кількість проливів. Це бонусні бали.",
"trait_temp": "Вода {v}°C",
"trait_pours": "Від {v} проливів",
"trait_pourtype": "Злив: {v}",
"vip_name": "Чайний критик",
"vip_av": "🧐",
"vip_badge": "Критик: подвійні бали",
"msg_vip": "Прийшов чайний критик! Терпіння менше, зате бали подвійні.",
"btn_brew": "Заварити чай і отримати бонус",
"btn_skip": "Пропустити",
"btn_info": "Інфо",
"btn_tried_short": "Вже було",
"cat_empty": "У цій категорії поки немає чаїв у твоєму меню.",
"brew_title": "Заварювання: {tea}",
"brew_q_temp": "Яка температура води потрібна цьому чаю?",
"brew_q_pours": "Скільки проливів витримує цей чай?",
"brew_temp_ok": "Температура {v}°C підходить. Правильний діапазон: {range}.",
"brew_temp_bad": "Температура {v}°C не підходить. Правильно: {range}.",
"brew_pours_ok": "Проливи: {v}. Точно!",
"brew_pours_near": "Проливи: {v}. Майже, чай витримує {n}.",
"brew_pours_bad": "Проливи: {v}. Насправді чай витримує {n}.",
"brew_total": "Бонус за заварювання: +{pts}",
"howto_7": "Іноді приходить чайний критик: терпіння менше, зате бали подвійні.",
"howto_8": "Гру збережено автоматично. Працює без інтернету.",
"visitor_1_av": "👨",
"visitor_1_name": "Олександр",
"visitor_2_av": "👨",
"visitor_2_name": "Андрій",
"visitor_3_av": "👨",
"visitor_3_name": "Сергій",
"visitor_4_av": "👨",
"visitor_4_name": "Дмитро",
"visitor_5_av": "👨",
"visitor_5_name": "Іван",
"visitor_6_av": "👨",
"visitor_6_name": "Микола",
"visitor_7_av": "👨",
"visitor_7_name": "Василь",
"visitor_8_av": "👨",
"visitor_8_name": "Петро",
"visitor_9_av": "👨",
"visitor_9_name": "Богдан",
"visitor_10_av": "👨",
"visitor_10_name": "Тарас",
"visitor_11_av": "👩",
"visitor_11_name": "Оксана",
"visitor_12_av": "👩",
"visitor_12_name": "Олена",
"visitor_13_av": "👩",
"visitor_13_name": "Марія",
"visitor_14_av": "👩",
"visitor_14_name": "Софія",
"visitor_15_av": "👩",
"visitor_15_name": "Анна",
"visitor_16_av": "👩",
"visitor_16_name": "Катерина",
"visitor_17_av": "👩",
"visitor_17_name": "Ірина",
"visitor_18_av": "👩",
"visitor_18_name": "Наталія",
"visitor_19_av": "👩",
"visitor_19_name": "Юлія",
"visitor_20_av": "👩",
"visitor_20_name": "Христина",
"visitor_21_av": "👨",
"visitor_21_name": "Wang Wei",
"visitor_22_av": "👩",
"visitor_22_name": "Li Na",
"visitor_23_av": "👩",
"visitor_23_name": "Zhang Min",
"visitor_24_av": "👨",
"visitor_24_name": "Liu Yang",
"visitor_25_av": "👩",
"visitor_25_name": "Chen Jing",
"visitor_26_av": "👨",
"visitor_26_name": "Yang Fan",
"visitor_27_av": "👨",
"visitor_27_name": "Zhao Lei",
"visitor_28_av": "👩",
"visitor_28_name": "Huang Ting",
"visitor_29_av": "👨",
"visitor_29_name": "Zhou Jie",
"visitor_30_av": "👩",
"visitor_30_name": "Wu Qian",
"visitor_31_av": "👨",
"visitor_31_name": "Xu Peng",
"visitor_32_av": "👩",
"visitor_32_name": "Sun Li",
"visitor_33_av": "👨",
"visitor_33_name": "Ma Chao",
"visitor_34_av": "👩",
"visitor_34_name": "Zhu Lin",
"visitor_35_av": "👨",
"visitor_35_name": "Hu Jun",
"visitor_36_av": "👩",
"visitor_36_name": "Guo Yan",
"visitor_37_av": "👨",
"visitor_37_name": "He Wei",
"visitor_38_av": "👨",
"visitor_38_name": "Gao Xiang",
"visitor_39_av": "👩",
"visitor_39_name": "Lin Fang",
"visitor_40_av": "👨",
"visitor_40_name": "Luo Chen",
"greeting": "Вітаю, я хочу:",
"btn_mini": "Міні-ігри",
"mini_title": "Міні-ігри",
"mini_sub": "Тренуй знання про чаї без гостей і без життів.",
"mini_best": "Рекорд: {n}",
"mg_exit": "Вийти",
"mg_again": "Ще раз",
"mg_home": "До міні-ігор",
"mg_done_title": "Гру завершено",
"mg_new_record": "Новий рекорд!",
"mg_res_score": "Рахунок",
"mg_res_mist": "Помилок",
"mg_res_best": "Найкращий рахунок",
"mg_next": "Далі",
"mg_check": "Перевірити",
"mg_right": "Правильно!",
"mg_wrong": "Не зовсім.",
"mg_sort_title": "Сортування",
"mg_sort_desc": "Розклади чаї по кошиках за правилом. П’ять карток, три правила.",
"mg_sort_rule": "Розклади за: {rule}",
"mg_sort_where": "Куди покласти цей чай?",
"mg_sort_wrong": "Ні. Правильний кошик: {bin}.",
"rule_type": "типом",
"rule_region": "регіоном",
"rule_char": "характером",
"rule_novice": "придатністю для новачків",
"rule_time": "часом доби",
"rule_pour": "зливом",
"rule_temp": "температурою води",
"rule_pours": "кількістю проливів",
"bin_novice_yes": "Для новачків",
"bin_novice_no": "Не для новачків",
"bin_temp_low": "Нижче 90°C",
"bin_temp_high": "90°C і вище",
"bin_pours_low": "До 6 проливів",
"bin_pours_high": "7 і більше проливів",
"mg_match_title": "Пари",
"mg_match_desc": "З’єднай чаї з їхніми властивостями.",
"mg_match_rule": "З’єднай чай і {what}.",
"match_temp": "температуру води",
"match_pours": "кількість проливів",
"match_region": "регіон",
"match_type": "тип",
"val_pours": "{n} проливів",
"mg_match_hint": "Торкнись чаю, а потім його пари.",
"mg_match_ok": "Пара!",
"mg_match_bad": "Не пара.",
"mg_tech_title": "Технологічна картка",
"mg_tech_desc": "Відновлюй втрачені дані на картках чаїв.",
"mg_tech_card": "Технологічна картка",
"mg_tech_fill": "Обери правильні значення для пунктів «???».",
"mg_tech_result": "Правильно: {ok} з {n}.",
"mg_odd_title": "Зайвий чай",
"mg_odd_desc": "Три чаї мають щось спільне. Знайди четвертий.",
"mg_odd_q": "Три чаї мають щось спільне. Який зайвий?",
"odd_type": "тип — {v}",
"odd_region": "регіон — {v}",
"odd_char": "характер — {v}",
"odd_novice": "усі підходять новачкам",
"odd_desc": "смак — {v}",
"odd_pour": "злив — {v}",
"odd_time": "час доби — {v}",
"mg_odd_common": "Спільне в трьох: {what}. Зайвий — «{tea}».",
"mg_guess_title": "Вгадай чай",
"mg_guess_desc": "Впізнай чай за трьома ознаками.",
"mg_guess_q": "Який чай має всі ці ознаки?",
"mg_guess_reveal": "Це «{tea}».",
"mg_order_title": "Сходинки",
"mg_order_desc": "Впорядкуй чаї за проливами й температурою.",
"mg_order_q_pours": "Впорядкуй чаї від найменшої кількості проливів до найбільшої.",
"mg_order_q_temp": "Впорядкуй чаї від найнижчої температури до найвищої.",
"mg_order_tap": "Торкайся чаїв по порядку.",
"mg_order_ok": "Порядок правильний!",
"mg_order_bad": "Ні, спочатку йде чай із меншим значенням.",
"howto_9": "У розділі «Міні-ігри» можна тренувати знання про чаї без гостей і без життів.",
"btn_learn": "Навчання",
"learn_title": "Навчання за категоріями",
"learn_sub": "Крок за кроком: вивчаєш кожен чай, розрізняєш чаї в групі й складаєш іспит категорії.",
"learn_known": "Вивчено чаїв (три зірки): {n} з {total}",
"learn_progress": "Зірок: {stars} з {max}",
"cat_teas": "Чаїв: {n}",
"cat_continue": "Продовжити",
"cat_steps": "Кроки категорії",
"row_overview": "Огляд категорії",
"row_overview_sub": "Що об’єднує чаї цієї групи",
"row_compare": "Порівняння в групі",
"row_compare_sub": "Чим схожі й чим відрізняються",
"row_exam": "Іспит категорії",
"row_exam_sub": "Розрізни чаї групи",
"row_exam_best": "Найкращий результат: {n} з {total}",
"row_start": "Почати",
"row_repeat": "Повторити",
"cat_single": "У цій категорії один чай, тому порівняння й іспит недоступні.",
"lesson_exit": "Вийти",
"lesson_next": "Далі",
"lesson_back": "Назад",
"lesson_finish": "Завершити",
"lesson_check": "Перевірити",
"lr_title": "Урок завершено",
"lr_cloze": "Пропуски",
"lr_quiz": "Запитання",
"lr_stars": "Зірки",
"lr_again": "Пройти ще раз",
"lr_to_cat": "До категорії",
"lr_verdict": "Результат",
"lr_exam_pass": "Іспит складено!",
"lr_exam_fail": "Потрібно щонайменше {need} з {n}. Спробуй ще раз.",
"page_who": "Хто це",
"page_taste": "Смак і аромат",
"page_brew": "Заварювання",
"page_when": "Кому й коли радити",
"page_story": "Про чай",
"page_pitch": "Як розповісти гостю",
"taste_tip": "Запам’ятай два-три головні смаки цього чаю.",
"brew_tip": "Ці числа треба знати напам’ять: температура, проливи, злив.",
"pitch_hint": "Прочитай уголос своїми словами, а потім перевір себе на пропусках і запитаннях.",
"pitch_who": "«{name}». Тип — {type}, регіон — {region}",
"pitch_char": ", характер — {char}",
"pitch_taste": "На смак і аромат: {list}.",
"pitch_brew": "Заварюємо так: {parts}.",
"pp_vessel": "посуд — {v}",
"pp_weight": "порція {v}",
"pp_temp": "вода {v}",
"pp_pours": "до {v} проливів",
"pp_pour": "злив — {v}",
"pitch_when": "Найкраще пити: {time}.",
"pitch_novice_yes": "Підходить новачкам.",
"pitch_novice_no": "Краще для досвідчених.",
"form_intro": "Відтвори з пам’яті: обери правильні значення.",
"form_result": "Правильно: {ok} з {n}.",
"f_region": "Регіон",
"f_taste": "Один зі смаків цього чаю",
"f_char": "Характер",
"f_tastes": "Смак",
"f_novice": "Для новачків",
"ans_yes": "Так",
"ans_no": "Ні",
"fb_right": "Правильно!",
"fb_wrong": "Не зовсім. Правильно: {ans}.",
"q_region": "Із якого регіону «{tea}»?",
"q_char": "Який характер у «{tea}»?",
"q_taste": "Який із цих смаків має «{tea}»?",
"q_temp": "Яка температура води для «{tea}»?",
"q_pours": "Скільки проливів витримує «{tea}»?",
"q_pour": "Який злив у «{tea}»?",
"q_vessel": "У чому заварюємо «{tea}»?",
"q_time": "Коли краще пити «{tea}»?",
"q_novice": "Чи підходить «{tea}» новачкам?",
"q_diff": "Що є правдою про «{a}», але не про «{b}»?",
"diff_desc": "має смак «{v}»",
"diff_region": "регіон — {v}",
"diff_char": "характер — {v}",
"diff_temp": "температура — {v}",
"diff_pours": "проливів: {v}",
"diff_pour": "злив — {v}",
"diff_novice_yes": "підходить новачкам",
"diff_novice_no": "не для новачків",
"exam_guess": "Який чай групи має всі ці ознаки?",
"ov_common": "Що об’єднує групу",
"ov_count": "Чаїв у групі: {n}.",
"ov_regions": "Регіони: {list}.",
"ov_temp": "Вода: від {lo} до {hi}°C.",
"ov_pours": "Проливи: від {lo} до {hi}.",
"ov_taste": "Найчастіші смаки: {list}.",
"ov_novice": "Для новачків: {n} з {total}.",
"ov_char": "Інтровертів: {a}, екстравертів: {b}.",
"ov_members": "Хто в групі",
"ov_member": "{name}: {region}, вода {temp}, проливів: {n}",
"oq_region": "Який регіон найчастіше зустрічається в категорії «{type}»?",
"oq_taste": "Який смак найчастіший у категорії «{type}»?",
"oq_novice": "Скільки чаїв категорії «{type}» підходять новачкам?",
"cmp_title": "«{a}» і «{b}»",
"cmp_hint": "Відмінності виділено кольором. Запам’ятай, за чим їх розрізняти.",
"howto_10": "У розділі «Навчання» кожна категорія має уроки: вивчаєш чаї, порівнюєш їх у групі й складаєш іспит."
};
